global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'bank-monolith'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # 'host.docker.internal' is used to scrape metrics from the host machine running Spring Boot
      - targets: ['host.docker.internal:8080']
